spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/users?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true # local
    # url: jdbc:mysql://mysql:3306/users?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true # docker-compose.yml 에서 환경변수 셋팅 하므로 사실 안바꿔도 됨
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!