server:
  port: 0

spring:
  application:
    name: user-service

  profiles:
    include: eureka, config, actuator, rabbitmq, zipkin, swagger, database


#logging:
#  level:
#    com.example.userservice.client: DEBUG