server:
  port: 3535

spring:
  application:
    name: user-service

  profiles:
    include: eureka, config, actuator, rabbitmq, zipkin, redis, swagger


#logging:
#  level:
#    com.example.userservice.client: DEBUG